export const zoneMapping = {
  'Aix-Marseille': 'B',
  Amiens: 'B',
  Besançon: 'A',
  Bordeaux: 'A',
  'Clermont-Ferrand': 'A',
  Corse: '',
  Créteil: 'C',
  Dijon: 'A',
  Grenoble: 'A',
  Guadeloupe: '',
  Guyane: '',
  'La Réunion': '',
  Lille: 'B',
  Limoges: 'A',
  Lyon: 'A',
  Martinique: '',
  Mayotte: '',
  Montpellier: 'C',
  'Nancy-Metz': 'B',
  Nantes: 'B',
  Nice: 'B',
  Normandie: 'B',
  'Nouvelle Calédonie': '',
  'Orléans-Tours': 'B',
  Paris: 'C',
  Poitiers: 'A',
  'Polynésie Française': '',
  Reims: 'B',
  Rennes: 'B',
  'Saint Pierre et Miquelon': '',
  Strasbourg: 'B',
  Toulouse: 'C',
  Versailles: 'C',
  'Wallis et Futuna': '',
};
