export const dirigentFilterMock = {
  results: [
    {
      siren: '533915427',
      nom_complet: 'SUPERMAN',
      nom_raison_sociale: null,
      sigle: null,
      nombre_etablissements: 3,
      nombre_etablissements_ouverts: 1,
      siege: {
        activite_principale: '96.09Z',
        activite_principale_registre_metier: null,
        adresse: '36 RUE DES PIPISRELLES 30190 LA CALMETTE',
        cedex: null,
        code_pays_etranger: null,
        code_postal: '30190',
        commune: '30061',
        complement_adresse: null,
        coordonnees: '43.925028,4.270067',
        date_creation: '2019-06-01',
        date_debut_activite: '2019-06-01',
        departement: '30',
        distribution_speciale: null,
        est_siege: true,
        etat_administratif: 'A',
        geo_adresse: '36 Rue des Pipistrelles 30190 La Calmette',
        geo_id: '30061_0401_00036',
        indice_repetition: null,
        latitude: '43.925028',
        libelle_cedex: null,
        libelle_commune: 'LA CALMETTE',
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: 'DES PIPISRELLES',
        liste_enseignes: null,
        liste_finess: null,
        liste_idcc: null,
        liste_rge: null,
        liste_uai: null,
        longitude: '4.270067',
        nom_commercial: null,
        numero_voie: '36',
        siret: '53391542700033',
        tranche_effectif_salarie: null,
        type_voie: 'RUE',
      },
      activite_principale: '96.09Z',
      categorie_entreprise: 'PME',
      date_creation: '2011-08-02',
      date_mise_a_jour: '2021-01-14T20:01:27',
      dirigeants: [
        {
          nom: 'HIDALGO',
          prenoms: 'ANNE',
          annee_de_naissance: null,
          qualite: null,
          type_dirigeant: 'personne physique',
        },
      ],
      etat_administratif: 'A',
      nature_juridique: '1000',
      section_activite_principale: 'S',
      tranche_effectif_salarie: null,
      matching_etablissements: [],
      complements: {
        collectivite_territoriale: null,
        convention_collective_renseignee: false,
        est_entrepreneur_individuel: true,
        est_entrepreneur_spectacle: false,
        est_ess: false,
        est_finess: false,
        est_rge: false,
        est_service_public: false,
        est_uai: false,
        identifiant_association: null,
      },
    },
    {
      siren: '200054781',
      nom_complet: 'METROPOLE DU GRAND PARIS (MGP)',
      nom_raison_sociale: 'METROPOLE DU GRAND PARIS',
      sigle: 'MGP',
      nombre_etablissements: 2,
      nombre_etablissements_ouverts: 1,
      siege: {
        activite_principale: '84.11Z',
        activite_principale_registre_metier: null,
        adresse: 'BATIMENT BE OPEN 15 AV PIERRE MENDES FRANCE 75013 PARIS 13',
        cedex: null,
        code_pays_etranger: null,
        code_postal: '75013',
        commune: '75113',
        complement_adresse: 'BATIMENT BE OPEN',
        coordonnees: '48.837285,2.370436',
        date_creation: '2016-12-28',
        date_debut_activite: '2016-12-28',
        departement: '75',
        distribution_speciale: null,
        est_siege: true,
        etat_administratif: 'A',
        geo_adresse: '15 Avenue Pierre Mendès France 75013 Paris',
        geo_id: '75113_7460_00015',
        indice_repetition: null,
        latitude: '48.837285',
        libelle_cedex: null,
        libelle_commune: 'PARIS 13',
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: 'PIERRE MENDES FRANCE',
        liste_enseignes: null,
        liste_finess: null,
        liste_idcc: ['5021'],
        liste_rge: null,
        liste_uai: null,
        longitude: '2.370436',
        nom_commercial: null,
        numero_voie: '15',
        siret: '20005478100022',
        tranche_effectif_salarie: '22',
        type_voie: 'AV',
      },
      activite_principale: '84.11Z',
      categorie_entreprise: 'PME',
      date_creation: '2016-01-01',
      date_mise_a_jour: '2022-08-29T09:05:12',
      dirigeants: [],
      etat_administratif: 'A',
      nature_juridique: '7344',
      section_activite_principale: 'O',
      tranche_effectif_salarie: '22',
      matching_etablissements: [],
      complements: {
        collectivite_territoriale: {
          code: '200054781',
          code_insee: null,
          elus: [
            {
              nom: 'AQUA',
              prenoms: 'Jean-Noël',
              annee_de_naissance: '1974',
              fonction: null,
              sexe: 'M',
            },
          ],
          niveau: 'epci',
        },
        convention_collective_renseignee: true,
        est_entrepreneur_individuel: false,
        est_entrepreneur_spectacle: false,
        est_ess: false,
        est_finess: false,
        est_rge: false,
        est_service_public: true,
        est_uai: false,
        identifiant_association: null,
      },
    },
  ],
  total_results: 8,
  page: 1,
  per_page: 10,
  total_pages: 1,
};
