/**
 * Entrepreneurs de Spectacles Vivants
 */
export const searchEsvMock = {
  results: [
    {
      siren: '399463603',
      nom_complet: "LE MELO D'AMELIE",
      nom_raison_sociale: "LE MELO D'AMELIE",
      sigle: null,
      nombre_etablissements: 1,
      nombre_etablissements_ouverts: 1,
      siege: {
        activite_principale: '90.01Z',
        activite_principale_registre_metier: null,
        adresse: '4 RUE MARIE STUART 75002 PARIS 2',
        cedex: null,
        code_pays_etranger: null,
        code_postal: '75002',
        commune: '75102',
        complement_adresse: null,
        coordonnees: '48.865018,2.348353',
        date_creation: '1994-12-16',
        date_debut_activite: '2008-01-01',
        departement: '75',
        distribution_speciale: null,
        est_siege: true,
        etat_administratif: 'A',
        geo_adresse: '4 Rue Marie Stuart 75002 Paris',
        geo_id: '75102_6084_00004',
        indice_repetition: null,
        latitude: '48.865018',
        libelle_cedex: null,
        libelle_commune: 'PARIS 2',
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: 'MARIE STUART',
        liste_enseignes: null,
        liste_finess: null,
        liste_id_bio: null,
        liste_idcc: ['3090'],
        liste_id_organisme_formation: null,
        liste_rge: null,
        liste_uai: null,
        longitude: '2.348353',
        nom_commercial: null,
        numero_voie: '4',
        siret: '39946360300015',
        tranche_effectif_salarie: '02',
        type_voie: 'RUE',
      },
      activite_principale: '90.01Z',
      categorie_entreprise: 'PME',
      date_creation: '1994-12-16',
      date_mise_a_jour: '2022-08-29T09:20:39',
      dirigeants: [
        {
          nom: 'LOPEZ',
          prenoms: 'jean-luc',
          annee_de_naissance: '1971',
          qualite: 'G\u00e9rant',
          type_dirigeant: 'personne physique',
        },
      ],
      etat_administratif: 'A',
      nature_juridique: '5499',
      section_activite_principale: 'R',
      tranche_effectif_salarie: '02',
      matching_etablissements: [],
      bilan_financier: {},
      complements: {
        bilan_renseigne: false,
        collectivite_territoriale: null,
        convention_collective_renseignee: true,
        egapro_renseignee: false,
        est_bio: false,
        est_entrepreneur_individuel: false,
        est_entrepreneur_spectacle: true,
        est_ess: false,
        est_finess: false,
        est_organisme_formation: false,
        est_rge: false,
        est_service_public: false,
        est_uai: false,
        identifiant_association: null,
        statut_bio: null,
        statut_entrepreneur_spectacle: 'invalide',
      },
      slug_annuaire_entreprises: 'le-melo-d-amelie-399463603',
      etablissements: [
        {
          activite_principale: '90.01Z',
          adresse: '4 RUE MARIE STUART 75002 PARIS 2',
          commune: '75102',
          est_siege: true,
          etat_administratif: 'A',
          geo_id: '75102_6084_00004',
          latitude: '48.865018',
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: ['3090'],
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: '2.348353',
          nom_commercial: null,
          siret: '39946360300015',
        },
      ],
    },
  ],
  total_results: 1,
  page: 1,
  per_page: 10,
  total_pages: 1,
};
