export const mainSearchMock = {
  results: [
    {
      siren: '533915427',
      nom_complet: 'ANNE HIDALGO',
      nom_raison_sociale: null,
      sigle: null,
      nombre_etablissements: 3,
      nombre_etablissements_ouverts: 1,
      siege: {
        activite_principale: '96.09Z',
        activite_principale_registre_metier: null,
        adresse: '36 RUE DES PIPISRELLES 30190 LA CALMETTE',
        cedex: null,
        code_pays_etranger: null,
        code_postal: '30190',
        commune: '30061',
        complement_adresse: null,
        coordonnees: '43.925028,4.270067',
        date_creation: '2019-06-01',
        date_debut_activite: '2019-06-01',
        departement: '30',
        distribution_speciale: null,
        est_siege: true,
        etat_administratif: 'A',
        geo_adresse: '36 Rue des Pipistrelles 30190 La Calmette',
        geo_id: '30061_0401_00036',
        indice_repetition: null,
        latitude: '43.925028',
        libelle_cedex: null,
        libelle_commune: 'LA CALMETTE',
        libelle_commune_etranger: null,
        libelle_pays_etranger: null,
        libelle_voie: 'DES PIPISRELLES',
        liste_enseignes: null,
        liste_finess: null,
        liste_idcc: null,
        liste_rge: null,
        liste_uai: null,
        longitude: '4.270067',
        nom_commercial: null,
        numero_voie: '36',
        siret: '53391542700033',
        tranche_effectif_salarie: null,
        type_voie: 'RUE',
      },
      activite_principale: '96.09Z',
      categorie_entreprise: 'PME',
      date_creation: '2011-08-02',
      date_mise_a_jour: '2021-01-14T20:01:27',
      dirigeants: [
        {
          nom: 'HIDALGO',
          prenoms: 'ANNE',
          annee_de_naissance: null,
          qualite: null,
          type_dirigeant: 'personne physique',
        },
      ],
      etat_administratif: 'A',
      nature_juridique: '1000',
      section_activite_principale: 'S',
      tranche_effectif_salarie: null,
      matching_etablissements: [
        {
          activite_principale: '96.09Z',
          adresse: '36 RUE DES PIPISRELLES 30190 LA CALMETTE',
          commune: '30061',
          est_siege: true,
          etat_administratif: 'A',
          geo_id: '30061_0401_00036',
          latitude: '43.925028',
          liste_enseignes: null,
          liste_finess: null,
          liste_idcc: null,
          liste_rge: null,
          liste_uai: null,
          longitude: '4.270067',
          nom_commercial: null,
          siret: '53391542700033',
        },
        {
          activite_principale: '82.11Z',
          adresse: '51 RUE DU CEVENOL 30730 FONS',
          commune: '30112',
          est_siege: false,
          etat_administratif: 'F',
          geo_id: '30112_0029_00051',
          latitude: '43.908036',
          liste_enseignes: null,
          liste_finess: null,
          liste_idcc: null,
          liste_rge: null,
          liste_uai: null,
          longitude: '4.204861',
          nom_commercial: null,
          siret: '53391542700017',
        },
        {
          activite_principale: '96.09Z',
          adresse: '150 CHE DE LA GARE A1 30730 SAINT-MAMERT-DU-GARD',
          commune: '30281',
          est_siege: false,
          etat_administratif: 'F',
          geo_id: '30281_0068_00150',
          latitude: '43.888297',
          liste_enseignes: null,
          liste_finess: null,
          liste_idcc: null,
          liste_rge: null,
          liste_uai: null,
          longitude: '4.190521',
          nom_commercial: null,
          siret: '53391542700025',
        },
      ],
      complements: {
        collectivite_territoriale: null,
        convention_collective_renseignee: false,
        est_entrepreneur_individuel: true,
        est_entrepreneur_spectacle: false,
        est_ess: false,
        est_finess: false,
        est_rge: false,
        est_service_public: false,
        est_uai: false,
        identifiant_association: null,
      },
    },
  ],
  total_results: 27,
  page: 1,
  per_page: 10,
  total_pages: 3,
};
