/**
 * This company is used in test for its status
 * (EN SOMMEIL OU PRÉSUMÉE INACTIVE)
 */
export default {
  match:
    'https://recherche-entreprises.api.gouv.fr/search?per_page=10&page=1&q=351556394',
  response: {
    results: [
      {
        siren: '351556394',
        nom_complet: 'FINASSUR',
        nom_raison_sociale: 'FINASSUR',
        sigle: null,
        nombre_etablissements: 1,
        nombre_etablissements_ouverts: 0,
        siege: {
          activite_principale: '66.22Z',
          activite_principale_registre_metier: null,
          adresse: 'RUELLE ALBERT CAMUS 1 IMP DES CAMISARDS 97420 LE PORT',
          cedex: null,
          code_pays_etranger: null,
          code_postal: '97420',
          commune: '97407',
          complement_adresse: 'RUELLE ALBERT CAMUS',
          coordonnees: '-20.939898,55.292697',
          date_creation: '1989-08-01',
          date_debut_activite: '2009-01-05',
          departement: '974',
          distribution_speciale: null,
          est_siege: true,
          etat_administratif: 'F',
          geo_adresse: '1 Impasse des Camisards 97420 Le Port',
          geo_id: '97407_0078_00001',
          indice_repetition: null,
          latitude: '-20.939898',
          libelle_cedex: null,
          libelle_commune: 'LE PORT',
          libelle_commune_etranger: null,
          libelle_pays_etranger: null,
          libelle_voie: 'DES CAMISARDS',
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: '55.292697',
          nom_commercial: null,
          numero_voie: '1',
          siret: '35155639400010',
          tranche_effectif_salarie: 'NN',
          type_voie: 'IMP',
        },
        activite_principale: '66.22Z',
        categorie_entreprise: null,
        date_creation: '1989-08-01',
        date_mise_a_jour: '2011-04-16T04:06:21',
        dirigeants: [],
        etat_administratif: 'A',
        nature_juridique: '5499',
        section_activite_principale: 'K',
        tranche_effectif_salarie: 'NN',
        matching_etablissements: [],
        complements: {
          collectivite_territoriale: null,
          convention_collective_renseignee: false,
          egapro_renseignee: false,
          est_bio: false,
          est_entrepreneur_individuel: false,
          est_entrepreneur_spectacle: false,
          est_ess: false,
          est_finess: false,
          est_organisme_formation: false,
          est_rge: false,
          est_service_public: false,
          est_uai: false,
          identifiant_association: null,
          statut_entrepreneur_spectacle: null,
        },
      },
    ],
    total_results: 1,
    page: 1,
    per_page: 10,
    total_pages: 1,
  },
};
