export default {
  match: [
    'https://recherche-entreprises.api.gouv.fr/search?per_page=10&page=1&q=880878145',
  ],
  response: {
    results: [
      {
        siren: '880878145',
        nom_complet: 'GANYMEDE',
        nom_raison_sociale: 'GANYMEDE',
        sigle: null,
        nombre_etablissements: 1,
        nombre_etablissements_ouverts: 0,
        siege: {
          activite_principale: '62.02A',
          activite_principale_registre_metier: null,
          adresse: '128 RUE LA BOETIE 75008 PARIS 8',
          cedex: null,
          code_pays_etranger: null,
          code_postal: '75008',
          commune: '75108',
          complement_adresse: null,
          coordonnees: '48.870938,2.305916',
          date_creation: '2020-01-13',
          date_debut_activite: '2022-10-22',
          departement: '75',
          distribution_speciale: null,
          est_siege: true,
          etat_administratif: 'F',
          geo_adresse: '128 Rue la Bo\u00e9tie 75008 Paris',
          geo_id: '75108_5194_00128',
          indice_repetition: null,
          latitude: '48.870938',
          libelle_cedex: null,
          libelle_commune: 'PARIS 8',
          libelle_commune_etranger: null,
          libelle_pays_etranger: null,
          libelle_voie: 'LA BOETIE',
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: '2.305916',
          nom_commercial: null,
          numero_voie: '128',
          siret: '88087814500015',
          tranche_effectif_salarie: '01',
          type_voie: 'RUE',
        },
        activite_principale: '62.02A',
        categorie_entreprise: 'PME',
        date_creation: '2020-01-13',
        date_mise_a_jour: '2022-11-16T04:20:08',
        dirigeants: [
          {
            nom: 'JOUPPE',
            prenoms: 'xavier marie erwan',
            annee_de_naissance: '1990',
            qualite: 'Pr\u00e9sident, Liquidateur',
            type_dirigeant: 'personne physique',
          },
        ],
        etat_administratif: 'C',
        nature_juridique: '5710',
        section_activite_principale: 'J',
        tranche_effectif_salarie: '01',
        matching_etablissements: [],
        complements: {
          collectivite_territoriale: null,
          convention_collective_renseignee: false,
          egapro_renseignee: false,
          est_bio: false,
          est_entrepreneur_individuel: false,
          est_entrepreneur_spectacle: false,
          est_ess: false,
          est_finess: false,
          est_organisme_formation: false,
          est_rge: false,
          est_service_public: false,
          est_uai: false,
          identifiant_association: null,
          statut_entrepreneur_spectacle: null,
        },
      },
    ],
    total_results: 1,
    page: 1,
    per_page: 10,
    total_pages: 1,
  },
};
