/**
 * This uniteLegale has the characteristics
 * ASSOCIATION | ESS | Entrepreneur de spectacles vivants
 */
export default {
  match: 'https://recherche-entreprises.api.gouv.fr/search?q=842019051',
  response: {
    results: [
      {
        siren: '842019051',
        nom_complet: 'MANAKIN PRODUCTION',
        nom_raison_sociale: 'MANAKIN PRODUCTION',
        sigle: null,
        nombre_etablissements: 1,
        nombre_etablissements_ouverts: 1,
        siege: {
          activite_principale: '90.01Z',
          activite_principale_registre_metier: null,
          adresse: 'MANAKIN PRODUCTION 129 RUE LAMARCK 75018 PARIS 18',
          cedex: null,
          code_pays_etranger: null,
          code_postal: '75018',
          commune: '75118',
          complement_adresse: 'MANAKIN PRODUCTION',
          coordonnees: '48.891022,2.329849',
          date_creation: '2018-08-02',
          date_debut_activite: '2018-12-26',
          departement: '75',
          distribution_speciale: null,
          est_siege: true,
          etat_administratif: 'A',
          geo_adresse: '129 Rue Lamarck 75018 Paris',
          geo_id: '75118_5288_00129',
          indice_repetition: null,
          latitude: '48.891022',
          libelle_cedex: null,
          libelle_commune: 'PARIS 18',
          libelle_commune_etranger: null,
          libelle_pays_etranger: null,
          libelle_voie: 'LAMARCK',
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: ['1285'],
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: '2.329849',
          nom_commercial: null,
          numero_voie: '129',
          siret: '84201905100015',
          tranche_effectif_salarie: '01',
          type_voie: 'RUE',
        },
        activite_principale: '90.01Z',
        categorie_entreprise: 'PME',
        date_creation: '2018-08-02',
        date_mise_a_jour: '2022-08-29T10:29:06',
        dirigeants: [],
        etat_administratif: 'A',
        nature_juridique: '9220',
        section_activite_principale: 'R',
        tranche_effectif_salarie: '01',
        matching_etablissements: [],
        complements: {
          collectivite_territoriale: null,
          convention_collective_renseignee: true,
          egapro_renseignee: false,
          est_bio: false,
          est_entrepreneur_individuel: false,
          est_entrepreneur_spectacle: true,
          est_ess: true,
          est_finess: false,
          est_organisme_formation: false,
          est_rge: false,
          est_service_public: false,
          est_uai: false,
          identifiant_association: 'W751245606',
          statut_entrepreneur_spectacle: 'valide',
        },
        etablissements: [
          {
            activite_principale: '90.01Z',
            adresse: 'MANAKIN PRODUCTION 129 RUE LAMARCK 75018 PARIS 18',
            commune: '75118',
            est_siege: true,
            etat_administratif: 'A',
            geo_id: '75118_5288_00129',
            latitude: '48.891022',
            libelle_commune: 'PARIS 18',
            liste_enseignes: null,
            liste_finess: null,
            liste_id_bio: null,
            liste_idcc: ['1285'],
            liste_id_organisme_formation: null,
            liste_rge: null,
            liste_uai: null,
            longitude: '2.329849',
            nom_commercial: null,
            siret: '84201905100015',
          },
        ],
        slug_annuaire_entreprises: 'manakin-production-842019051',
      },
    ],
    total_results: 1,
    page: 1,
    per_page: 10,
    total_pages: 1,
  },
};
