/**
 * This company is used in test for its status
 * (Entreprise individuelle diffusible)
 */
export default {
  match:
    'https://recherche-entreprises.api.gouv.fr/search?per_page=10&page=1&q=883010316',
  response: {
    results: [
      {
        siren: '883010316',
        nom_complet: 'RAPHAEL DUBIGNY',
        nom_raison_sociale: null,
        sigle: null,
        nombre_etablissements: 1,
        nombre_etablissements_ouverts: 0,
        siege: {
          activite_principale: '70.22Z',
          activite_principale_registre_metier: null,
          adresse: 'RED NEEDLES 17 RUE DE FRANCEVILLE 93220 GAGNY',
          cedex: null,
          code_pays_etranger: null,
          code_postal: '93220',
          commune: '93032',
          complement_adresse: 'RED NEEDLES',
          coordonnees: '48.886494,2.542338',
          date_creation: '2018-05-06',
          date_debut_activite: '2020-09-01',
          departement: '93',
          distribution_speciale: null,
          est_siege: true,
          etat_administratif: 'F',
          geo_adresse: '17 Rue de Franceville 93220 Gagny',
          geo_id: '93032_1230_00017',
          indice_repetition: null,
          latitude: '48.886494',
          libelle_cedex: null,
          libelle_commune: 'GAGNY',
          libelle_commune_etranger: null,
          libelle_pays_etranger: null,
          libelle_voie: 'DE FRANCEVILLE',
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: '2.542338',
          nom_commercial: null,
          numero_voie: '17',
          siret: '88301031600015',
          tranche_effectif_salarie: null,
          type_voie: 'RUE',
        },
        activite_principale: '70.22Z',
        categorie_entreprise: 'PME',
        date_creation: '2018-05-06',
        date_mise_a_jour: '2022-10-31T09:00:33',
        dirigeants: [
          {
            nom: 'DUBIGNY',
            prenoms: 'RAPHAEL',
            annee_de_naissance: null,
            qualite: null,
            type_dirigeant: 'personne physique',
          },
        ],
        etat_administratif: 'C',
        nature_juridique: '1000',
        section_activite_principale: 'M',
        tranche_effectif_salarie: null,
        matching_etablissements: [],
        complements: {
          collectivite_territoriale: null,
          convention_collective_renseignee: false,
          egapro_renseignee: false,
          est_bio: false,
          est_entrepreneur_individuel: true,
          est_entrepreneur_spectacle: false,
          est_ess: false,
          est_finess: false,
          est_organisme_formation: false,
          est_rge: false,
          est_service_public: false,
          est_uai: false,
          identifiant_association: null,
          statut_entrepreneur_spectacle: null,
        },
      },
    ],
    total_results: 1,
    page: 1,
    per_page: 10,
    total_pages: 1,
  },
};
