/**
 * This uniteLegale is used in test for its (non diffusible) status
 */
export default {
  match: 'https://recherche-entreprises.api.gouv.fr/search?q=300025764',
  response: {
    results: [
      {
        siren: '300025764',
        nom_complet: '[ND] ([ND] [ND] [ND]) ([ND])',
        nom_raison_sociale: '[ND]',
        sigle: '[ND]',
        nombre_etablissements: 2,
        nombre_etablissements_ouverts: 1,
        siege: {
          activite_principale: '68.20A',
          activite_principale_registre_metier: null,
          adresse: '[ND] [ND] [ND] [ND] [ND] [ND] [ND] [ND]',
          cedex: '[ND]',
          code_pays_etranger: null,
          code_postal: '[ND]',
          commune: '35238',
          complement_adresse: '[ND]',
          coordonnees: null,
          date_creation: '2019-12-23',
          date_debut_activite: '2019-12-23',
          departement: '35',
          distribution_speciale: '[ND]',
          est_siege: true,
          etat_administratif: 'A',
          geo_adresse: null,
          geo_id: null,
          indice_repetition: '[ND]',
          latitude: null,
          libelle_cedex: '[ND]',
          libelle_commune: 'RENNES',
          libelle_commune_etranger: null,
          libelle_pays_etranger: null,
          libelle_voie: '[ND]',
          liste_enseignes: ['[ND]', '[ND]', '[ND]'],
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: null,
          liste_uai: null,
          longitude: null,
          nom_commercial: '[ND]',
          numero_voie: '[ND]',
          siret: '30002576400048',
          tranche_effectif_salarie: null,
          type_voie: '[ND]',
        },
        activite_principale: '68.20A',
        categorie_entreprise: 'PME',
        date_creation: '1981-10-01',
        date_mise_a_jour: '2020-04-08T15:04:45',
        dirigeants: [
          {
            nom: '[ND] ([ND])',
            prenoms: '[ND]',
            annee_de_naissance: null,
            qualite: null,
            type_dirigeant: 'personne physique',
          },
        ],
        etat_administratif: 'A',
        nature_juridique: '1000',
        section_activite_principale: 'L',
        tranche_effectif_salarie: 'NN',
        matching_etablissements: [],
        complements: {
          collectivite_territoriale: null,
          convention_collective_renseignee: false,
          egapro_renseignee: false,
          est_bio: false,
          est_entrepreneur_individuel: true,
          est_entrepreneur_spectacle: false,
          est_ess: false,
          est_finess: false,
          est_organisme_formation: false,
          est_rge: false,
          est_service_public: false,
          est_uai: false,
          identifiant_association: null,
          statut_entrepreneur_spectacle: null,
        },
      },
    ],
    total_results: 1,
    page: 1,
    per_page: 10,
    total_pages: 1,
  },
};
