/**
 * This uniteLegale has the characteristics
 * (RGE)
 */
export default {
  match:
    'https://recherche-entreprises.api.gouv.fr/search?per_page=10&page=1&q=528163777',
  response: {
    results: [
      {
        siren: '528163777',
        nom_complet: 'COMPANY WITH RGE CERTIFICATIONS',
        nom_raison_sociale: 'COMPANY WITH RGE CERTIFICATIONS',
        sigle: 'G.S.E.P.T.',
        nombre_etablissements: 4,
        nombre_etablissements_ouverts: 2,
        siege: {
          activite_principale: '43.22B',
          activite_principale_registre_metier: null,
          adresse: '5-9 5 RUE MORAND 93400 SAINT-OUEN-SUR-SEINE',
          cedex: null,
          code_pays_etranger: null,
          code_postal: '93400',
          commune: '93070',
          complement_adresse: '5-9',
          coordonnees: '48.903483,2.347786',
          date_creation: '2013-10-18',
          date_debut_activite: '2013-10-18',
          departement: '93',
          distribution_speciale: null,
          est_siege: true,
          etat_administratif: 'C',
          geo_adresse: '5 Rue Morand 93400 Saint-Ouen-sur-Seine',
          geo_id: '93070_6178_00005',
          indice_repetition: null,
          latitude: '48.903483',
          libelle_cedex: null,
          libelle_commune: 'SAINT-OUEN-SUR-SEINE',
          libelle_commune_etranger: null,
          libelle_pays_etranger: null,
          libelle_voie: 'MORAND',
          liste_enseignes: null,
          liste_finess: null,
          liste_id_bio: null,
          liste_idcc: null,
          liste_id_organisme_formation: null,
          liste_rge: ['C001D117', 'C001D119', '1911'],
          liste_uai: null,
          longitude: '2.347786',
          nom_commercial: null,
          numero_voie: '5',
          siret: '52816377700030',
          tranche_effectif_salarie: '11',
          type_voie: 'RUE',
        },
        activite_principale: '71.12B',
        categorie_entreprise: 'PME',
        date_creation: '2010-10-01',
        date_mise_a_jour: '2022-10-24T08:35:03',
        dirigeants: [
          {
            siren: '878719756',
            denomination: 'GSE VD',
            sigle: null,
            qualite: 'Pr\u00e9sident',
            type_dirigeant: 'personne morale',
          },
        ],
        etat_administratif: 'A',
        nature_juridique: '5710',
        section_activite_principale: 'M',
        tranche_effectif_salarie: '11',
        matching_etablissements: [],
        bilan_financier: {
          ca: 4984159.0,
          resultat_net: 66146.0,
          date_cloture_exercice: '2021-09-30',
        },
        complements: {
          bilan_renseigne: true,
          collectivite_territoriale: null,
          convention_collective_renseignee: false,
          egapro_renseignee: false,
          est_bio: false,
          est_entrepreneur_individuel: false,
          est_entrepreneur_spectacle: false,
          est_ess: false,
          est_finess: false,
          est_organisme_formation: false,
          est_rge: true,
          est_service_public: false,
          est_uai: false,
          identifiant_association: null,
          statut_bio: null,
          statut_entrepreneur_spectacle: null,
        },
        slug_annuaire_entreprises:
          'groupe-solution-energie-pole-technique-g-s-e-p-t-528163777',
        etablissements: [
          {
            activite_principale: '43.22B',
            adresse:
              "ZONE TERTIAIRE D'ATLANPARC 1 RUE CAMILLE CLAUDEL 56890 PLESCOP",
            commune: '56158',
            est_siege: false,
            etat_administratif: 'A',
            geo_id: '56158_0017_00001',
            latitude: '47.678137',
            liste_enseignes: null,
            liste_finess: null,
            liste_id_bio: null,
            liste_idcc: null,
            liste_id_organisme_formation: null,
            liste_rge: null,
            liste_uai: null,
            longitude: '-2.801441',
            nom_commercial: null,
            siret: '52816377700048',
          },
          {
            activite_principale: '43.22B',
            adresse: '16 QUAI GUSTAVE FLAUBERT 76380 CANTELEU',
            commune: '76157',
            est_siege: false,
            etat_administratif: 'F',
            geo_id: '76157_0211_00016',
            latitude: '49.43363',
            liste_enseignes: null,
            liste_finess: null,
            liste_id_bio: null,
            liste_idcc: null,
            liste_id_organisme_formation: null,
            liste_rge: null,
            liste_uai: null,
            longitude: '1.029039',
            nom_commercial: null,
            siret: '52816377700022',
          },
          {
            activite_principale: '43.22B',
            adresse:
              '155-159 155 RUE DU DOCTEUR BAUER 93400 SAINT-OUEN-SUR-SEINE',
            commune: '93070',
            est_siege: false,
            etat_administratif: 'F',
            geo_id: '93070_2582_00155',
            latitude: '48.903545',
            liste_enseignes: null,
            liste_finess: null,
            liste_id_bio: null,
            liste_idcc: null,
            liste_id_organisme_formation: null,
            liste_rge: null,
            liste_uai: null,
            longitude: '2.347099',
            nom_commercial: null,
            siret: '52816377700014',
          },
          {
            activite_principale: '43.22B',
            adresse: '5-9 5 RUE MORAND 93400 SAINT-OUEN-SUR-SEINE',
            commune: '93070',
            est_siege: true,
            etat_administratif: 'A',
            geo_id: '93070_6178_00005',
            latitude: '48.903483',
            liste_enseignes: null,
            liste_finess: null,
            liste_id_bio: null,
            liste_idcc: null,
            liste_id_organisme_formation: null,
            liste_rge: ['C001D117', 'C001D119', '1911'],
            liste_uai: null,
            longitude: '2.347786',
            nom_commercial: null,
            siret: '52816377700030',
          },
        ],
      },
    ],
    total_results: 1,
    page: 1,
    per_page: 10,
    total_pages: 1,
  },
};
