/**
 * This uniteLegale has the characteristics
 * (EN SOMMEIL OU PRÉSUMÉE INACTIVE)
 */
export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siren/351556394',
  response: {
    header: {
      statut: 200,
      message: 'OK',
    },
    uniteLegale: {
      siren: '351556394',
      statutDiffusionUniteLegale: 'O',
      dateCreationUniteLegale: '1989-08-01',
      sigleUniteLegale: null,
      sexeUniteLegale: null,
      prenom1UniteLegale: null,
      prenom2UniteLegale: null,
      prenom3UniteLegale: null,
      prenom4UniteLegale: null,
      prenomUsuelUniteLegale: null,
      pseudonymeUniteLegale: null,
      identifiantAssociationUniteLegale: null,
      trancheEffectifsUniteLegale: 'NN',
      anneeEffectifsUniteLegale: null,
      dateDernierTraitementUniteLegale: '2011-04-16T04:06:21',
      nombrePeriodesUniteLegale: 3,
      categorieEntreprise: null,
      anneeCategorieEntreprise: null,
      periodesUniteLegale: [
        {
          dateFin: null,
          dateDebut: '2008-01-01',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'FINASSUR',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5499',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '66.22Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: true,
          nicSiegeUniteLegale: '00010',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2007-12-31',
          dateDebut: '1989-12-25',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'FINASSUR',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5499',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '67.2Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAF1993',
          changementActivitePrincipaleUniteLegale: true,
          nicSiegeUniteLegale: '00010',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '1989-12-24',
          dateDebut: '1989-08-01',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'FINASSUR',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5499',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: null,
          nomenclatureActivitePrincipaleUniteLegale: null,
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00010',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
      ],
    },
  },
};
