export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siren/880878145',
  response: {
    header: {
      statut: 200,
      message: 'OK',
    },
    uniteLegale: {
      siren: '880878145',
      statutDiffusionUniteLegale: 'O',
      dateCreationUniteLegale: '2020-01-13',
      sigleUniteLegale: null,
      sexeUniteLegale: null,
      prenom1UniteLegale: null,
      prenom2UniteLegale: null,
      prenom3UniteLegale: null,
      prenom4UniteLegale: null,
      prenomUsuelUniteLegale: null,
      pseudonymeUniteLegale: null,
      identifiantAssociationUniteLegale: null,
      trancheEffectifsUniteLegale: '01',
      anneeEffectifsUniteLegale: '2020',
      dateDernierTraitementUniteLegale: '2022-11-16T04:20:08',
      nombrePeriodesUniteLegale: 4,
      categorieEntreprise: 'PME',
      anneeCategorieEntreprise: '2020',
      periodesUniteLegale: [
        {
          dateFin: null,
          dateDebut: '2022-10-22',
          etatAdministratifUniteLegale: 'C',
          changementEtatAdministratifUniteLegale: true,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'GANYMEDE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5710',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '62.02A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00015',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: 'N',
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2022-10-21',
          dateDebut: '2021-12-31',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'GANYMEDE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5710',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '62.02A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00015',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: 'N',
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: true,
        },
        {
          dateFin: '2021-12-30',
          dateDebut: '2020-03-01',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'GANYMEDE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5710',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '62.02A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00015',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: 'N',
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'O',
          changementCaractereEmployeurUniteLegale: true,
        },
        {
          dateFin: '2020-02-29',
          dateDebut: '2020-01-13',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'GANYMEDE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5710',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '62.02A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00015',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: 'N',
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
      ],
    },
  },
};
