export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siren/356000000',
  response: {
    header: {
      statut: 200,
      message: 'OK',
    },
    uniteLegale: {
      siren: '356000000',
      statutDiffusionUniteLegale: 'O',
      dateCreationUniteLegale: '1991-01-01',
      sigleUniteLegale: null,
      sexeUniteLegale: null,
      prenom1UniteLegale: null,
      prenom2UniteLegale: null,
      prenom3UniteLegale: null,
      prenom4UniteLegale: null,
      prenomUsuelUniteLegale: null,
      pseudonymeUniteLegale: null,
      identifiantAssociationUniteLegale: null,
      trancheEffectifsUniteLegale: '53',
      anneeEffectifsUniteLegale: '2020',
      dateDernierTraitementUniteLegale: '2023-03-16T03:58:53',
      nombrePeriodesUniteLegale: 9,
      categorieEntreprise: 'GE',
      anneeCategorieEntreprise: '2020',
      periodesUniteLegale: [
        {
          dateFin: null,
          dateDebut: '2021-12-31',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5510',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '53.10Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: 'N',
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: 'N',
          changementSocieteMissionUniteLegale: true,
          caractereEmployeurUniteLegale: 'O',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2021-12-30',
          dateDebut: '2021-06-08',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5510',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '53.10Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: 'N',
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: 'O',
          changementSocieteMissionUniteLegale: true,
          caractereEmployeurUniteLegale: 'O',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2021-06-07',
          dateDebut: '2018-06-01',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5510',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '53.10Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: 'N',
          changementEconomieSocialeSolidaireUniteLegale: true,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'O',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2018-05-31',
          dateDebut: '2010-02-26',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5510',
          changementCategorieJuridiqueUniteLegale: true,
          activitePrincipaleUniteLegale: '53.10Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'O',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2010-02-25',
          dateDebut: '2008-01-01',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '4130',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '53.10Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: true,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'O',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2007-12-31',
          dateDebut: '2005-11-26',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '4130',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '64.1A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev1',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'O',
          changementCaractereEmployeurUniteLegale: true,
        },
        {
          dateFin: '2005-11-25',
          dateDebut: '2003-01-01',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '4130',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '64.1A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAF1993',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: true,
        },
        {
          dateFin: '2002-12-31',
          dateDebut: '1991-12-25',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '4130',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '64.1A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAF1993',
          changementActivitePrincipaleUniteLegale: true,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: null,
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '1991-12-24',
          dateDebut: '1991-01-01',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'LA POSTE',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: 'DIRECTION GENERALE DE LA POSTE',
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '4130',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: null,
          nomenclatureActivitePrincipaleUniteLegale: null,
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00048',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: null,
          changementCaractereEmployeurUniteLegale: false,
        },
      ],
    },
  },
};
