/**
 * This company is used in test for its status
 * (Entreprise individuelle diffusible)
 */
export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siren/883010316',
  response: {
    header: {
      statut: 200,
      message: 'OK',
    },
    uniteLegale: {
      siren: '883010316',
      statutDiffusionUniteLegale: 'O',
      dateCreationUniteLegale: '2018-05-06',
      sigleUniteLegale: null,
      sexeUniteLegale: 'M',
      prenom1UniteLegale: 'RAPHAEL',
      prenom2UniteLegale: null,
      prenom3UniteLegale: null,
      prenom4UniteLegale: null,
      prenomUsuelUniteLegale: 'RAPHAEL',
      pseudonymeUniteLegale: null,
      identifiantAssociationUniteLegale: null,
      trancheEffectifsUniteLegale: null,
      anneeEffectifsUniteLegale: null,
      dateDernierTraitementUniteLegale: '2022-10-31T09:00:33',
      nombrePeriodesUniteLegale: 2,
      categorieEntreprise: 'PME',
      anneeCategorieEntreprise: '2020',
      periodesUniteLegale: [
        {
          dateFin: null,
          dateDebut: '2020-09-01',
          etatAdministratifUniteLegale: 'C',
          changementEtatAdministratifUniteLegale: true,
          nomUniteLegale: 'DUBIGNY',
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: null,
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '1000',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '70.22Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00015',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2020-08-31',
          dateDebut: '2018-05-06',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: 'DUBIGNY',
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: null,
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '1000',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '70.22Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00015',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
      ],
    },
  },
};
