/**
 * This company is used in test for its status
 * (CESSÉE)
 */
export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siren/839517323',
  response: {
    header: {
      statut: 200,
      message: 'OK',
    },
    uniteLegale: {
      siren: '839517323',
      statutDiffusionUniteLegale: 'O',
      dateCreationUniteLegale: '2018-05-06',
      sigleUniteLegale: null,
      sexeUniteLegale: null,
      prenom1UniteLegale: null,
      prenom2UniteLegale: null,
      prenom3UniteLegale: null,
      prenom4UniteLegale: null,
      prenomUsuelUniteLegale: null,
      pseudonymeUniteLegale: null,
      identifiantAssociationUniteLegale: null,
      trancheEffectifsUniteLegale: null,
      anneeEffectifsUniteLegale: null,
      dateDernierTraitementUniteLegale: '2021-10-16T08:42:44',
      nombrePeriodesUniteLegale: 2,
      categorieEntreprise: 'PME',
      anneeCategorieEntreprise: '2020',
      periodesUniteLegale: [
        {
          dateFin: null,
          dateDebut: '2021-10-11',
          etatAdministratifUniteLegale: 'C',
          changementEtatAdministratifUniteLegale: true,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'RED NEEDLES',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5499',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '62.02A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00011',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
        {
          dateFin: '2021-10-10',
          dateDebut: '2018-05-06',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'RED NEEDLES',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5499',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '62.02A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00011',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: null,
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: null,
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'N',
          changementCaractereEmployeurUniteLegale: false,
        },
      ],
    },
  },
};
