/**
 * This uniteLegale has the characteristics
 * (PROTECTED)
 */
export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siren/908595879',
  response: {
    header: {
      statut: 200,
      message: 'OK',
    },
    uniteLegale: {
      siren: '908595879',
      statutDiffusionUniteLegale: 'O',
      dateCreationUniteLegale: '2022-01-01',
      sigleUniteLegale: null,
      sexeUniteLegale: null,
      prenom1UniteLegale: null,
      prenom2UniteLegale: null,
      prenom3UniteLegale: null,
      prenom4UniteLegale: null,
      prenomUsuelUniteLegale: null,
      pseudonymeUniteLegale: null,
      identifiantAssociationUniteLegale: null,
      trancheEffectifsUniteLegale: null,
      anneeEffectifsUniteLegale: null,
      dateDernierTraitementUniteLegale: '2022-07-13T10:40:59',
      nombrePeriodesUniteLegale: 1,
      categorieEntreprise: null,
      anneeCategorieEntreprise: null,
      periodesUniteLegale: [
        {
          dateFin: null,
          dateDebut: '2022-01-01',
          etatAdministratifUniteLegale: 'A',
          changementEtatAdministratifUniteLegale: false,
          nomUniteLegale: null,
          changementNomUniteLegale: false,
          nomUsageUniteLegale: null,
          changementNomUsageUniteLegale: false,
          denominationUniteLegale: 'SEVERNAYA',
          changementDenominationUniteLegale: false,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          changementDenominationUsuelleUniteLegale: false,
          categorieJuridiqueUniteLegale: '5710',
          changementCategorieJuridiqueUniteLegale: false,
          activitePrincipaleUniteLegale: '70.21Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          changementActivitePrincipaleUniteLegale: false,
          nicSiegeUniteLegale: '00010',
          changementNicSiegeUniteLegale: false,
          economieSocialeSolidaireUniteLegale: 'N',
          changementEconomieSocialeSolidaireUniteLegale: false,
          societeMissionUniteLegale: 'N',
          changementSocieteMissionUniteLegale: false,
          caractereEmployeurUniteLegale: 'O',
          changementCaractereEmployeurUniteLegale: false,
        },
      ],
    },
  },
};
