interface IBilanGesItem {
  __id: number;
  actions_et_moyens: string;
  aide_diag_decarbonaction: boolean;
  analyse_des_resultats_obtenus: string;
  annee_de_reporting: number;
  apenaf_associe: string;
  assujetti_dpefpcaet: boolean;
  code_departement: string;
  comparaison_avec_le_precedent_bilan: string;
  complement_dinformation_sur_les_energies_garanties_dorigine_etou_renouvelables: string;
  courriel: string;
  date_de_publication: string;
  departement: string;
  des_emissions_evitees_ont_ete_calculees_pour: string;
  emissions_publication_p11: number;
  emissions_publication_p12: number;
  emissions_publication_p13: number;
  emissions_publication_p14: number;
  emissions_publication_p15: number;
  emissions_publication_p21: number;
  emissions_publication_p22: number;
  emissions_publication_p31: number;
  emissions_publication_p32: number;
  emissions_publication_p33: number;
  emissions_publication_p34: number;
  emissions_publication_p35: number;
  emissions_publication_p41: number;
  emissions_publication_p42: number;
  emissions_publication_p43: number;
  emissions_publication_p44: number;
  emissions_publication_p45: number;
  emissions_publication_p51: number;
  emissions_publication_p52: number;
  emissions_publication_p53: number;
  emissions_publication_p54: number;
  emissions_publication_p61: number;
  emissions_reference_p11: number;
  emissions_reference_p12: number;
  emissions_reference_p13: number;
  emissions_reference_p14: number;
  emissions_reference_p15: number;
  emissions_reference_p21: number;
  emissions_reference_p22: number;
  emissions_reference_p31: number;
  emissions_reference_p32: number;
  emissions_reference_p33: number;
  emissions_reference_p34: number;
  emissions_reference_p35: number;
  emissions_reference_p41: number;
  emissions_reference_p42: number;
  emissions_reference_p43: number;
  emissions_reference_p44: number;
  emissions_reference_p45: number;
  emissions_reference_p51: number;
  emissions_reference_p52: number;
  emissions_reference_p53: number;
  emissions_reference_p54: number;
  emissions_reference_p61: number;
  engagement_du_personnel: boolean;
  fonction: string;
  id: string;
  importance_strategique_et_vulnerabilites: boolean;
  incertitudes: string;
  justification_des_postes_demissions_indirectes_ecartes: string;
  libelle: string;
  lien_dpefpcaet: string;
  lien_url_vers_le_rapport_complet_du_beges: string;
  lignes_directrices_specifiques_au_secteur: boolean;
  liste_des_facteurs_demission_fe_et_pouvoir_de_rechauffement_global_prg_utilises: string;
  methode_beges_v4v5: string;
  mode_de_consolidation: string;
  niveau_dinfluence: boolean;
  nombre_de_salariesdagents: string;
  objectif_emissions_directes: string;
  objectif_emissions_indirectes_significatives: string;
  objectif_pour_2030: string;
  objectif_pour_2050: string;
  objectifs_a_dautres_horizons_temporels: string;
  part_de_lenergie_garantie_dorigine_etou_renouvelable_dans_la_consommation_denergie: string;
  politique_developpement_durable: string;
  population: string;
  presentation_de_lorganisation: string;
  raison_sociale: string;
  recalcul: string;
  region: string;
  responsable_du_suivi: string;
  seuil_dimportance_retenu: string;
  siren_principal: string;
  siret: string;
  sources: string;
  soustraitance: boolean;
  structure_obligee: boolean;
  telephone: string;
  type_de_collectivite: string;
  type_de_structure: string;
  une_annee_de_reference_a_ete_calculee: boolean;
}

interface IBilanGesDatagouvResponse {
  next: string | null;
  results: IBilanGesItem[];
  total: number;
}

interface IBilanGes {
  actionsEtMoyens: string;
  anneeReporting: number;
  autresEmissionsIndirectes: number;
  codeAPE: string;
  courriel: string;
  datePublication: string;
  departement: string;
  emissionsDirectes: number;
  emissionsIndirectesEnergie: number;
  fonction: string;
  id: string;
  libelle: string;
  lienRapportComplet: string;
  methodeBEGES: string;
  modeConsolidation: string;
  nombreSalaries: string;
  objectifsPour2030: string;
  objectifsPour2050: string;
  politiqueDeveloppementDurable: string;
  presentationOrganisation: string;
  raisonSociale: string;
  region: string;
  responsableSuivi: string;
  sirenPrincipal: string;
  structureObligee: boolean;
  telephone: string;
  totalEmissions: number;
  typeStructure: string;
}

interface IBilanGesResponse {
  data: IBilanGes[];
  meta: {
    total: number;
    next: string | null;
  };
}
