export type IOrganismesFormationRecord = {
  informationsdeclarees_datedernieredeclaration: string; // '25/05/2022';
  random_id: number; //39.00095797706437;
  informationsdeclarees_debutexercice: string; //  '01/01/2021';
  certifications: string; //  'Actions de formations/Actions de formations par apprentissage';
  geocodageban: number[]; //  [48.871778, 2.337854];
  certifications_bilansdecompetences: string; // 'false';
  reg_name: string; // 'Île-de-France';
  dep_name: string; // 'Paris';
  certifications_actionsdeformationparapprentissage: string; // 'true';
  organisme_formation_geocode: string; // 'True';
  certifications_vae: string; // 'false';
  toutes_specialites: string; //  'Enseignement, formation/Développement des capacités mentales et apprentissages de base/Développement des capacités comportementales et relationnelles';
  dep_code: string; // '75';
  siren: string; //  '662042449';
  denomination: string; //  'BNP  PARIBAS';
  adressephysiqueorganismeformation_voie: string; //  '16 bd des italiens';
  siretetablissementdeclarant: string; //  '66204244900014';
  adressephysiqueorganismeformation_ville: string; //  'PARIS 09';
  adressephysiqueorganismeformation_codepostal: string; //  '75009';
  certifications_actionsdeformation: string; //  'true';
  adressephysiqueorganismeformation_coderegion: string; //  '11';
  epci_name: string; //  'Métropole du Grand Paris';
  epci_code: string; //  '200054781';
  numerosdeclarationactiviteprecedent: string; //  '11754007375';
  numerodeclarationactivite: string; //  '11754007375';
  informationsdeclarees_specialitesdeformation_libellespecialite3: string; //  'Développement des capacités comportementales et relationnelles';
  informationsdeclarees_specialitesdeformation_codespecialite3: string; //  '413';
  com_arm_name: string; //  'Paris 9e Arrondissement';
  com_arm_code: string; //  '75109';
  reg_code: 11;
  informationsdeclarees_specialitesdeformation_libellespecialite1: string; //  'Enseignement, formation';
  informationsdeclarees_specialitesdeformation_codespecialite1: string; //  '333';
  informationsdeclarees_finexercice: string; //  '2021-12-31';
  informationsdeclarees_specialitesdeformation_libellespecialite2: string; //  'Développement des capacités mentales et apprentissages de base';
  informationsdeclarees_specialitesdeformation_codespecialite2: string; //  '412';
  informationsdeclarees_effectifformateurs: number; // 25;
  informationsdeclarees_nbstagiairesconfiesparunautreof: number; // 0;
  informationsdeclarees_nbstagiaires: number; // 697;
};
