export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siret/?q=siren:880878145',
  response: {
    header: {
      statut: 200,
      message: 'OK',
      total: 1,
      debut: 0,
      nombre: 1,
    },
    etablissements: [
      {
        siren: '880878145',
        nic: '00015',
        siret: '88087814500015',
        statutDiffusionEtablissement: 'O',
        dateCreationEtablissement: '2020-01-13',
        trancheEffectifsEtablissement: '01',
        anneeEffectifsEtablissement: '2020',
        activitePrincipaleRegistreMetiersEtablissement: null,
        dateDernierTraitementEtablissement: '2022-11-16T04:20:08',
        etablissementSiege: true,
        nombrePeriodesEtablissement: 4,
        uniteLegale: {
          etatAdministratifUniteLegale: 'C',
          statutDiffusionUniteLegale: 'O',
          dateCreationUniteLegale: '2020-01-13',
          categorieJuridiqueUniteLegale: '5710',
          denominationUniteLegale: 'GANYMEDE',
          sigleUniteLegale: null,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          sexeUniteLegale: null,
          nomUniteLegale: null,
          nomUsageUniteLegale: null,
          prenom1UniteLegale: null,
          prenom2UniteLegale: null,
          prenom3UniteLegale: null,
          prenom4UniteLegale: null,
          prenomUsuelUniteLegale: null,
          pseudonymeUniteLegale: null,
          activitePrincipaleUniteLegale: '62.02A',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          identifiantAssociationUniteLegale: null,
          economieSocialeSolidaireUniteLegale: 'N',
          societeMissionUniteLegale: null,
          caractereEmployeurUniteLegale: 'N',
          trancheEffectifsUniteLegale: '01',
          anneeEffectifsUniteLegale: '2020',
          nicSiegeUniteLegale: '00015',
          dateDernierTraitementUniteLegale: '2022-11-16T04:20:08',
          categorieEntreprise: 'PME',
          anneeCategorieEntreprise: '2020',
        },
        adresseEtablissement: {
          complementAdresseEtablissement: null,
          numeroVoieEtablissement: '128',
          indiceRepetitionEtablissement: null,
          typeVoieEtablissement: 'RUE',
          libelleVoieEtablissement: 'LA BOETIE',
          codePostalEtablissement: '75008',
          libelleCommuneEtablissement: 'PARIS 8',
          libelleCommuneEtrangerEtablissement: null,
          distributionSpecialeEtablissement: null,
          codeCommuneEtablissement: '75108',
          codeCedexEtablissement: null,
          libelleCedexEtablissement: null,
          codePaysEtrangerEtablissement: null,
          libellePaysEtrangerEtablissement: null,
        },
        adresse2Etablissement: {
          complementAdresse2Etablissement: null,
          numeroVoie2Etablissement: null,
          indiceRepetition2Etablissement: null,
          typeVoie2Etablissement: null,
          libelleVoie2Etablissement: null,
          codePostal2Etablissement: null,
          libelleCommune2Etablissement: null,
          libelleCommuneEtranger2Etablissement: null,
          distributionSpeciale2Etablissement: null,
          codeCommune2Etablissement: null,
          codeCedex2Etablissement: null,
          libelleCedex2Etablissement: null,
          codePaysEtranger2Etablissement: null,
          libellePaysEtranger2Etablissement: null,
        },
        periodesEtablissement: [
          {
            dateFin: null,
            dateDebut: '2022-10-22',
            etatAdministratifEtablissement: 'F',
            changementEtatAdministratifEtablissement: true,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '62.02A',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'N',
            changementCaractereEmployeurEtablissement: false,
          },
          {
            dateFin: '2022-10-21',
            dateDebut: '2021-12-31',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '62.02A',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'N',
            changementCaractereEmployeurEtablissement: true,
          },
          {
            dateFin: '2021-12-30',
            dateDebut: '2020-03-01',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '62.02A',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: true,
          },
          {
            dateFin: '2020-02-29',
            dateDebut: '2020-01-13',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '62.02A',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'N',
            changementCaractereEmployeurEtablissement: false,
          },
        ],
      },
    ],
  },
};
