/**
 * This uniteLegale has the characteristics
 * (PROTECTED)
 */
export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siret/q=siren:908595879',
  response: {
    header: {
      statut: 200,
      message: 'OK',
      total: 1,
      debut: 0,
      nombre: 1,
    },
    etablissements: [
      {
        siren: '908595879',
        nic: '00010',
        siret: '90859587900010',
        statutDiffusionEtablissement: 'O',
        dateCreationEtablissement: '2022-01-01',
        trancheEffectifsEtablissement: null,
        anneeEffectifsEtablissement: null,
        activitePrincipaleRegistreMetiersEtablissement: null,
        dateDernierTraitementEtablissement: '2022-07-13T10:40:59',
        etablissementSiege: true,
        nombrePeriodesEtablissement: 1,
        uniteLegale: {
          etatAdministratifUniteLegale: 'A',
          statutDiffusionUniteLegale: 'O',
          dateCreationUniteLegale: '2022-01-01',
          categorieJuridiqueUniteLegale: '5710',
          denominationUniteLegale: 'SEVERNAYA',
          sigleUniteLegale: null,
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          sexeUniteLegale: null,
          nomUniteLegale: null,
          nomUsageUniteLegale: null,
          prenom1UniteLegale: null,
          prenom2UniteLegale: null,
          prenom3UniteLegale: null,
          prenom4UniteLegale: null,
          prenomUsuelUniteLegale: null,
          pseudonymeUniteLegale: null,
          activitePrincipaleUniteLegale: '70.21Z',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          identifiantAssociationUniteLegale: null,
          economieSocialeSolidaireUniteLegale: 'N',
          societeMissionUniteLegale: 'N',
          caractereEmployeurUniteLegale: 'O',
          trancheEffectifsUniteLegale: null,
          anneeEffectifsUniteLegale: null,
          nicSiegeUniteLegale: '00010',
          dateDernierTraitementUniteLegale: '2022-07-13T10:40:59',
          categorieEntreprise: null,
          anneeCategorieEntreprise: null,
        },
        adresseEtablissement: {
          complementAdresseEtablissement: null,
          numeroVoieEtablissement: '10',
          indiceRepetitionEtablissement: null,
          typeVoieEtablissement: 'RUE',
          libelleVoieEtablissement: 'DE PENTHIEVRE',
          codePostalEtablissement: '75008',
          libelleCommuneEtablissement: 'PARIS 8',
          libelleCommuneEtrangerEtablissement: null,
          distributionSpecialeEtablissement: null,
          codeCommuneEtablissement: '75108',
          codeCedexEtablissement: null,
          libelleCedexEtablissement: null,
          codePaysEtrangerEtablissement: null,
          libellePaysEtrangerEtablissement: null,
        },
        adresse2Etablissement: {
          complementAdresse2Etablissement: null,
          numeroVoie2Etablissement: null,
          indiceRepetition2Etablissement: null,
          typeVoie2Etablissement: null,
          libelleVoie2Etablissement: null,
          codePostal2Etablissement: null,
          libelleCommune2Etablissement: null,
          libelleCommuneEtranger2Etablissement: null,
          distributionSpeciale2Etablissement: null,
          codeCommune2Etablissement: null,
          codeCedex2Etablissement: null,
          libelleCedex2Etablissement: null,
          codePaysEtranger2Etablissement: null,
          libellePaysEtranger2Etablissement: null,
        },
        periodesEtablissement: [
          {
            dateFin: null,
            dateDebut: '2022-01-01',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '70.21Z',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: false,
          },
        ],
      },
    ],
  },
};
