/**
 * This uniteLegale has the characteristics
 * (RGE)
 */
export default {
  match: 'https://api.insee.fr/entreprises/sirene/V3/siret/?q=siren:528163777',
  response: {
    header: {
      statut: 200,
      message: 'OK',
      total: 4,
      debut: 0,
      nombre: 4,
    },
    etablissements: [
      {
        siren: '528163777',
        nic: '00048',
        siret: '52816377700048',
        statutDiffusionEtablissement: 'O',
        dateCreationEtablissement: '2019-01-01',
        trancheEffectifsEtablissement: '01',
        anneeEffectifsEtablissement: '2020',
        activitePrincipaleRegistreMetiersEtablissement: null,
        dateDernierTraitementEtablissement: '2022-10-24T08:35:03',
        etablissementSiege: false,
        nombrePeriodesEtablissement: 3,
        uniteLegale: {
          etatAdministratifUniteLegale: 'A',
          statutDiffusionUniteLegale: 'O',
          dateCreationUniteLegale: '2010-10-01',
          categorieJuridiqueUniteLegale: '5710',
          denominationUniteLegale: 'GROUPE SOLUTION ENERGIE POLE TECHNIQUE',
          sigleUniteLegale: 'G.S.E.P.T.',
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          sexeUniteLegale: null,
          nomUniteLegale: null,
          nomUsageUniteLegale: null,
          prenom1UniteLegale: null,
          prenom2UniteLegale: null,
          prenom3UniteLegale: null,
          prenom4UniteLegale: null,
          prenomUsuelUniteLegale: null,
          pseudonymeUniteLegale: null,
          activitePrincipaleUniteLegale: '71.12B',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          identifiantAssociationUniteLegale: null,
          economieSocialeSolidaireUniteLegale: 'N',
          societeMissionUniteLegale: 'N',
          caractereEmployeurUniteLegale: 'O',
          trancheEffectifsUniteLegale: '11',
          anneeEffectifsUniteLegale: '2020',
          nicSiegeUniteLegale: '00030',
          dateDernierTraitementUniteLegale: '2022-10-24T08:35:03',
          categorieEntreprise: 'PME',
          anneeCategorieEntreprise: '2020',
        },
        adresseEtablissement: {
          complementAdresseEtablissement: "ZONE TERTIAIRE D'ATLANPARC",
          numeroVoieEtablissement: '1',
          indiceRepetitionEtablissement: null,
          typeVoieEtablissement: 'RUE',
          libelleVoieEtablissement: 'CAMILLE CLAUDEL',
          codePostalEtablissement: '56890',
          libelleCommuneEtablissement: 'PLESCOP',
          libelleCommuneEtrangerEtablissement: null,
          distributionSpecialeEtablissement: null,
          codeCommuneEtablissement: '56158',
          codeCedexEtablissement: null,
          libelleCedexEtablissement: null,
          codePaysEtrangerEtablissement: null,
          libellePaysEtrangerEtablissement: null,
        },
        adresse2Etablissement: {
          complementAdresse2Etablissement: null,
          numeroVoie2Etablissement: null,
          indiceRepetition2Etablissement: null,
          typeVoie2Etablissement: null,
          libelleVoie2Etablissement: null,
          codePostal2Etablissement: null,
          libelleCommune2Etablissement: null,
          libelleCommuneEtranger2Etablissement: null,
          distributionSpeciale2Etablissement: null,
          codeCommune2Etablissement: null,
          codeCedex2Etablissement: null,
          libelleCedex2Etablissement: null,
          codePaysEtranger2Etablissement: null,
          libellePaysEtranger2Etablissement: null,
        },
        periodesEtablissement: [
          {
            dateFin: null,
            dateDebut: '2022-07-31',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '43.22B',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'N',
            changementCaractereEmployeurEtablissement: true,
          },
          {
            dateFin: '2022-07-30',
            dateDebut: '2019-03-18',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '43.22B',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: true,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: false,
          },
          {
            dateFin: '2019-03-17',
            dateDebut: '2019-01-01',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '95.22Z',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: false,
          },
        ],
      },
      {
        siren: '528163777',
        nic: '00014',
        siret: '52816377700014',
        statutDiffusionEtablissement: 'O',
        dateCreationEtablissement: '2010-10-01',
        trancheEffectifsEtablissement: 'NN',
        anneeEffectifsEtablissement: null,
        activitePrincipaleRegistreMetiersEtablissement: null,
        dateDernierTraitementEtablissement: '2019-01-08T10:19:43',
        etablissementSiege: false,
        nombrePeriodesEtablissement: 3,
        uniteLegale: {
          etatAdministratifUniteLegale: 'A',
          statutDiffusionUniteLegale: 'O',
          dateCreationUniteLegale: '2010-10-01',
          categorieJuridiqueUniteLegale: '5710',
          denominationUniteLegale: 'GROUPE SOLUTION ENERGIE POLE TECHNIQUE',
          sigleUniteLegale: 'G.S.E.P.T.',
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          sexeUniteLegale: null,
          nomUniteLegale: null,
          nomUsageUniteLegale: null,
          prenom1UniteLegale: null,
          prenom2UniteLegale: null,
          prenom3UniteLegale: null,
          prenom4UniteLegale: null,
          prenomUsuelUniteLegale: null,
          pseudonymeUniteLegale: null,
          activitePrincipaleUniteLegale: '71.12B',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          identifiantAssociationUniteLegale: null,
          economieSocialeSolidaireUniteLegale: 'N',
          societeMissionUniteLegale: 'N',
          caractereEmployeurUniteLegale: 'O',
          trancheEffectifsUniteLegale: '11',
          anneeEffectifsUniteLegale: '2020',
          nicSiegeUniteLegale: '00030',
          dateDernierTraitementUniteLegale: '2022-10-24T08:35:03',
          categorieEntreprise: 'PME',
          anneeCategorieEntreprise: '2020',
        },
        adresseEtablissement: {
          complementAdresseEtablissement: '155-159',
          numeroVoieEtablissement: '155',
          indiceRepetitionEtablissement: null,
          typeVoieEtablissement: 'RUE',
          libelleVoieEtablissement: 'DU DOCTEUR BAUER',
          codePostalEtablissement: '93400',
          libelleCommuneEtablissement: 'SAINT-OUEN-SUR-SEINE',
          libelleCommuneEtrangerEtablissement: null,
          distributionSpecialeEtablissement: null,
          codeCommuneEtablissement: '93070',
          codeCedexEtablissement: null,
          libelleCedexEtablissement: null,
          codePaysEtrangerEtablissement: null,
          libellePaysEtrangerEtablissement: null,
        },
        adresse2Etablissement: {
          complementAdresse2Etablissement: null,
          numeroVoie2Etablissement: null,
          indiceRepetition2Etablissement: null,
          typeVoie2Etablissement: null,
          libelleVoie2Etablissement: null,
          codePostal2Etablissement: null,
          libelleCommune2Etablissement: null,
          libelleCommuneEtranger2Etablissement: null,
          distributionSpeciale2Etablissement: null,
          codeCommune2Etablissement: null,
          codeCedex2Etablissement: null,
          libelleCedex2Etablissement: null,
          codePaysEtranger2Etablissement: null,
          libellePaysEtranger2Etablissement: null,
        },
        periodesEtablissement: [
          {
            dateFin: null,
            dateDebut: '2013-10-18',
            etatAdministratifEtablissement: 'F',
            changementEtatAdministratifEtablissement: true,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '43.22B',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: false,
          },
          {
            dateFin: '2013-10-17',
            dateDebut: '2010-11-10',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '43.22B',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: true,
          },
          {
            dateFin: '2010-11-09',
            dateDebut: '2010-10-01',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '43.22B',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'N',
            changementCaractereEmployeurEtablissement: false,
          },
        ],
      },
      {
        siren: '528163777',
        nic: '00022',
        siret: '52816377700022',
        statutDiffusionEtablissement: 'O',
        dateCreationEtablissement: '2011-01-01',
        trancheEffectifsEtablissement: 'NN',
        anneeEffectifsEtablissement: null,
        activitePrincipaleRegistreMetiersEtablissement: null,
        dateDernierTraitementEtablissement: '2015-05-14T08:43:37',
        etablissementSiege: false,
        nombrePeriodesEtablissement: 2,
        uniteLegale: {
          etatAdministratifUniteLegale: 'A',
          statutDiffusionUniteLegale: 'O',
          dateCreationUniteLegale: '2010-10-01',
          categorieJuridiqueUniteLegale: '5710',
          denominationUniteLegale: 'GROUPE SOLUTION ENERGIE POLE TECHNIQUE',
          sigleUniteLegale: 'G.S.E.P.T.',
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          sexeUniteLegale: null,
          nomUniteLegale: null,
          nomUsageUniteLegale: null,
          prenom1UniteLegale: null,
          prenom2UniteLegale: null,
          prenom3UniteLegale: null,
          prenom4UniteLegale: null,
          prenomUsuelUniteLegale: null,
          pseudonymeUniteLegale: null,
          activitePrincipaleUniteLegale: '71.12B',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          identifiantAssociationUniteLegale: null,
          economieSocialeSolidaireUniteLegale: 'N',
          societeMissionUniteLegale: 'N',
          caractereEmployeurUniteLegale: 'O',
          trancheEffectifsUniteLegale: '11',
          anneeEffectifsUniteLegale: '2020',
          nicSiegeUniteLegale: '00030',
          dateDernierTraitementUniteLegale: '2022-10-24T08:35:03',
          categorieEntreprise: 'PME',
          anneeCategorieEntreprise: '2020',
        },
        adresseEtablissement: {
          complementAdresseEtablissement: null,
          numeroVoieEtablissement: '16',
          indiceRepetitionEtablissement: null,
          typeVoieEtablissement: 'QUAI',
          libelleVoieEtablissement: 'GUSTAVE FLAUBERT',
          codePostalEtablissement: '76380',
          libelleCommuneEtablissement: 'CANTELEU',
          libelleCommuneEtrangerEtablissement: null,
          distributionSpecialeEtablissement: null,
          codeCommuneEtablissement: '76157',
          codeCedexEtablissement: null,
          libelleCedexEtablissement: null,
          codePaysEtrangerEtablissement: null,
          libellePaysEtrangerEtablissement: null,
        },
        adresse2Etablissement: {
          complementAdresse2Etablissement: null,
          numeroVoie2Etablissement: null,
          indiceRepetition2Etablissement: null,
          typeVoie2Etablissement: null,
          libelleVoie2Etablissement: null,
          codePostal2Etablissement: null,
          libelleCommune2Etablissement: null,
          libelleCommuneEtranger2Etablissement: null,
          distributionSpeciale2Etablissement: null,
          codeCommune2Etablissement: null,
          codeCedex2Etablissement: null,
          libelleCedex2Etablissement: null,
          codePaysEtranger2Etablissement: null,
          libellePaysEtranger2Etablissement: null,
        },
        periodesEtablissement: [
          {
            dateFin: null,
            dateDebut: '2014-01-16',
            etatAdministratifEtablissement: 'F',
            changementEtatAdministratifEtablissement: true,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '43.22B',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: false,
          },
          {
            dateFin: '2014-01-15',
            dateDebut: '2011-01-01',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '43.22B',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: false,
          },
        ],
      },
      {
        siren: '528163777',
        nic: '00030',
        siret: '52816377700030',
        statutDiffusionEtablissement: 'O',
        dateCreationEtablissement: '2013-10-18',
        trancheEffectifsEtablissement: '11',
        anneeEffectifsEtablissement: '2020',
        activitePrincipaleRegistreMetiersEtablissement: null,
        dateDernierTraitementEtablissement: '2022-08-29T09:28:45',
        etablissementSiege: true,
        nombrePeriodesEtablissement: 1,
        uniteLegale: {
          etatAdministratifUniteLegale: 'A',
          statutDiffusionUniteLegale: 'O',
          dateCreationUniteLegale: '2010-10-01',
          categorieJuridiqueUniteLegale: '5710',
          denominationUniteLegale: 'GROUPE SOLUTION ENERGIE POLE TECHNIQUE',
          sigleUniteLegale: 'G.S.E.P.T.',
          denominationUsuelle1UniteLegale: null,
          denominationUsuelle2UniteLegale: null,
          denominationUsuelle3UniteLegale: null,
          sexeUniteLegale: null,
          nomUniteLegale: null,
          nomUsageUniteLegale: null,
          prenom1UniteLegale: null,
          prenom2UniteLegale: null,
          prenom3UniteLegale: null,
          prenom4UniteLegale: null,
          prenomUsuelUniteLegale: null,
          pseudonymeUniteLegale: null,
          activitePrincipaleUniteLegale: '71.12B',
          nomenclatureActivitePrincipaleUniteLegale: 'NAFRev2',
          identifiantAssociationUniteLegale: null,
          economieSocialeSolidaireUniteLegale: 'N',
          societeMissionUniteLegale: 'N',
          caractereEmployeurUniteLegale: 'O',
          trancheEffectifsUniteLegale: '11',
          anneeEffectifsUniteLegale: '2020',
          nicSiegeUniteLegale: '00030',
          dateDernierTraitementUniteLegale: '2022-10-24T08:35:03',
          categorieEntreprise: 'PME',
          anneeCategorieEntreprise: '2020',
        },
        adresseEtablissement: {
          complementAdresseEtablissement: '5-9',
          numeroVoieEtablissement: '5',
          indiceRepetitionEtablissement: null,
          typeVoieEtablissement: 'RUE',
          libelleVoieEtablissement: 'MORAND',
          codePostalEtablissement: '93400',
          libelleCommuneEtablissement: 'SAINT-OUEN-SUR-SEINE',
          libelleCommuneEtrangerEtablissement: null,
          distributionSpecialeEtablissement: null,
          codeCommuneEtablissement: '93070',
          codeCedexEtablissement: null,
          libelleCedexEtablissement: null,
          codePaysEtrangerEtablissement: null,
          libellePaysEtrangerEtablissement: null,
        },
        adresse2Etablissement: {
          complementAdresse2Etablissement: null,
          numeroVoie2Etablissement: null,
          indiceRepetition2Etablissement: null,
          typeVoie2Etablissement: null,
          libelleVoie2Etablissement: null,
          codePostal2Etablissement: null,
          libelleCommune2Etablissement: null,
          libelleCommuneEtranger2Etablissement: null,
          distributionSpeciale2Etablissement: null,
          codeCommune2Etablissement: null,
          codeCedex2Etablissement: null,
          libelleCedex2Etablissement: null,
          codePaysEtranger2Etablissement: null,
          libellePaysEtranger2Etablissement: null,
        },
        periodesEtablissement: [
          {
            dateFin: null,
            dateDebut: '2013-10-18',
            etatAdministratifEtablissement: 'A',
            changementEtatAdministratifEtablissement: false,
            enseigne1Etablissement: null,
            enseigne2Etablissement: null,
            enseigne3Etablissement: null,
            changementEnseigneEtablissement: false,
            denominationUsuelleEtablissement: null,
            changementDenominationUsuelleEtablissement: false,
            activitePrincipaleEtablissement: '43.22B',
            nomenclatureActivitePrincipaleEtablissement: 'NAFRev2',
            changementActivitePrincipaleEtablissement: false,
            caractereEmployeurEtablissement: 'O',
            changementCaractereEmployeurEtablissement: false,
          },
        ],
      },
    ],
  },
};
