export const certificatLogo = {
  'QUALIBAT-RGE': 'qualibat.jpg',
  'QualiPAC Chauffage': 'qualiPAC.jpg',
  'Qualibois module Eau': 'qualiBois.jpg',
  'Certificat OPQIBI': 'opqibi.jpg',
  'Qualibois module Air': 'qualiBois.jpg',
  'Chauffage +': 'chauffage.jpg',
  'Qualisol CESI': 'qalifelec.jpg',
  'QualiPV 36': 'qualiPV.jpg',
  'Ventilation +': 'ventillation.jpg',
  'Qualisol Combi': 'qualisol.jpg',
  'QualiPAC module CET': 'qualiPAC.jpg',
  'QualiPV 500': 'qualiPV.jpg',
  'CERTIBAT-RGE': 'certibat.jpg',
  ' NF HABITAT Rénovation Maison RGE par CERQUAL': 'NF.jpg',
  'Qualiforage module Sonde': 'aualiForage.jpg',
  'Qualiforage module Nappe': 'aualiForage.jpg',
  'Qualisol Collectif': 'qualisol.jpg',
};
