import { Question } from '#components-ui/question';
import { NPSBanner } from '#components/banner/nps';
import Footer from '#components/footer';
import { Header } from '#components/header';
import SocialNetworks from '#components/social-network';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id="">
          <NPSBanner />

          <Header
            useSearchBar={false}
            useAdvancedSearch={false}
            useMap={false}
          />
          <main className="fr-container">{children}</main>
          <SocialNetworks />
          <Question />
          <Footer />
        </div>
      </body>
    </html>
  );
}
