import { Metadata } from 'next';
import { Question } from '#components-ui/question';
import { NPSBanner } from '#components/banner/nps';
import Footer from '#components/footer';
import { Header } from '#components/header';
import SocialNetworks from '#components/social-network';
import '../frontend/style/dsfr.min.css';
import '../frontend/style/globals.css';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div style={{ width: '100%' }}>
          <NPSBanner />
          <Header
            useSearchBar={false}
            useAdvancedSearch={false}
            useMap={false}
            useAgentCTA={true}
          />
          <main className="fr-container">{children}</main>
          <SocialNetworks />
          <Question />
          <Footer />
        </div>
      </body>
    </html>
  );
}
