name: 'Notify message'
description: 'Send message to tech team'

inputs:
  hook:
    description: 'Hook url'
    required: true
  message:
    description: 'Body'
    required: true
  id:
    description: 'Room id'
    required: false

runs:
  using: 'composite'

  steps:
    - run: |
        curl -X POST ${{ inputs.hook }} -H 'Content-Type: application/json' -d '{ "message": "${{ inputs.message }}", "roomId": "${{ inputs.id }}" }'
      shell: bash
