name: 'Notify message'

runs:
  using: 'composite'

  steps:
    - name:
      run: |
        curl -X POST ${{ inputs.hook }} -d '{ "message": "${{ inputs.message }}", "roomId": "${{ inputs.id }}" }'
      shell: bash
