name: 'Notify message'

inputs:
  hooks:
    description: 'Hook url'
    required: true
  message:
    description: 'Body'
    required: true
  id:
    required: false

runs:
  using: 'composite'

  steps:
    - name:
      run: |
        curl -X POST ${{ inputs.hook }} -d '{ "message": "${{ inputs.message }}", "roomId": "${{ inputs.id }}" }'
      shell: bash
