export enum APIRoutesPaths {
  EspaceAgentConformite = 'espace-agent/conformite',
  EspaceAgentOpqibi = 'espace-agent/opqibi',
  EspaceAgentQualibat = 'espace-agent/qualibat',
  EspaceAgentQualifelec = 'espace-agent/qualifelec',
  EspaceAgentDirigeantsProtected = 'espace-agent/dirigeants-protected',
  EspaceAgentBeneficiaires = 'espace-agent/beneficiaires',
  EspaceAgentRneDocuments = 'espace-agent/rne/documents',
  EspaceAgentAssociationProtected = 'espace-agent/association-protected',
  EspaceAgentEffectifsAnnuelsProtected = 'espace-agent/effectifs-annuels-protected',
  EspaceAgentChiffreAffairesProtected = 'espace-agent/chiffre-affaires-protected',
  EspaceAgentTravauxPublics = 'espace-agent/travaux-publics',
  EspaceAgentBilansProtected = 'espace-agent/bilans-protected',
  EspaceAgentLiassesFiscalesProtected = 'espace-agent/liasses-fiscales-protected',
  RneDirigeants = 'rne-dirigeants',
  Observations = 'observations',
  Association = 'association',
  VerifyTva = 'verify-tva',
  EoriValidation = 'eori-validation',
  SubventionsAssociation = 'subventions-association',
}
