# This workflow will run a11y's tests on staging

name: A11y on staging

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 1 * * *'

jobs:
  recipe:
    name: A11y tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          npx pa11y-ci --config ../../pa11y.config.json
