# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Proxy PDF de l’extrait d’immatriculation INPI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# be extrremly careful as env variable defined here are accessible by all the actions of the workflow.
# For critical env variable declare it within the action
env:
  INSEE_CLIENT_ID: ${{ secrets.INSEE_CLIENT_ID }}
  INSEE_CLIENT_SECRET: ${{ secrets.INSEE_CLIENT_SECRET}}
  INSEE_CLIENT_ID_FALLBACK: ${{ secrets.INSEE_CLIENT_ID_FALLBACK }}
  INSEE_CLIENT_SECRET_FALLBACK: ${{ secrets.INSEE_CLIENT_SECRET_FALLBACK}}
  INPI_LOGIN: ${{ secrets.INPI_LOGIN}}
  INPI_PASSWORD: ${{ secrets.INPI_PASSWORD}}
  INPI_SITE_LOGIN: ${{ secrets.INPI_SITE_LOGIN}}
  INPI_SITE_PASSWORD: ${{ secrets.INPI_SITE_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build-dev
      - run: npm run start &
        env:
          PORT: 3000

      # wait for the server to start responding. We expect Bad Request 400 once it starts listening.
      # so override the shell and have the last command be the : { null } command to force exit code 0.
      - run: wget --retry-connrefused --waitretry=5 --read-timeout=10 --timeout=15 -t 50 http://localhost:3000/comment-ca-marche

      - run: |
          npm run test:inpi-pdf-proxy
