name: 'Deploy ciblé'
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      tag:
        description: "hash de commit ou nom de branche à déployer"
        required: true

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          case "${{ github.event.inputs.environment }}" in
            "production")
              echo 'matrix={"include":[{"environment":"production-01","host":"SSH_PRODUCTION_01"},{"environment":"production-02","host":"SSH_PRODUCTION_02"},{"environment":"production-03","host":"SSH_PRODUCTION_03"}]}' >> $GITHUB_OUTPUT
              ;;
            "staging")
              echo 'matrix={"include":[{"environment":"staging-01","host":"SSH_HOST_STAGING_V2"},{"environment":"staging-02","host":"SSH_STAGING_02"},{"environment":"staging-03","host":"SSH_STAGING_03"},{"environment":"staging-04","host":"SSH_STAGING_04"},]}' >> $GITHUB_OUTPUT
              ;;
          esac

  deploy:
    name: Deploy
    needs: set-matrix
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    timeout-minutes: 15
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
      - uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/deploy@v2.0
        with:
          app: "site"
          version: "${{ github.event.inputs.tag }}"
          environment: "${{ matrix.environment }}"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_APP_DEPLOYER }}
          ssh-host: ${{ secrets[matrix.host] }}
          notify-on-failure: true
          notify-on-success: true
          tchap-url: ${{ secrets.TCHAP_URL }}
          tchap-token: ${{ secrets.TCHAP_TOKEN }}
