name: Test Notify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  deploy-staging:
    name: Deploy - staging
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Notify staging failure only
        if: success() || failure()
        uses: ./.github/actions/notify
        with:
          message: '🚨 ${{ github.event.repository.name }} : deploy to staging failed'
          hook: ${{ secrets.TCHAP_HOOK }}
          id: ${{ secrets.TCHAP_ROOM_ID }}
