# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests End to End

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# be extrremly careful as env variable defined here are accessible by all the actions of the workflow.
# For critical env variable declare it within the action
env:
  INSEE_CLIENT_ID: ${{ secrets.INSEE_CLIENT_ID }}
  INSEE_CLIENT_SECRET: ${{ secrets.INSEE_CLIENT_SECRET}}
  INSEE_CLIENT_ID_FALLBACK: ${{ secrets.INSEE_CLIENT_ID_FALLBACK }}
  INSEE_CLIENT_SECRET_FALLBACK: ${{ secrets.INSEE_CLIENT_SECRET_FALLBACK}}
  INPI_LOGIN: ${{ secrets.INPI_LOGIN}}
  INPI_PASSWORD: ${{ secrets.INPI_PASSWORD}}
  INPI_SITE_LOGIN: ${{ secrets.INPI_SITE_LOGIN}}
  INPI_SITE_PASSWORD: ${{ secrets.INPI_SITE_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          build: npm run build
          start: npm start
        env:
          PORT: 3000
