name: 'User feedbacks report'
permissions:
  contents: read

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Create and post feedbacks report
        run: |
          npm i node-fetch && GRIST_TABLE=${{ secrets.GRIST_FEEDBACKS_TABLE }} GRIST_API_KEY=${{ secrets.GRIST_API_KEY }}  HOOK=${{ secrets.FEEDBACKS_HOOK }} node ./scripts/feedbacks/index.mjs

      - name: Notify failure
        if: failure()
        uses: ./.github/actions/notify
        with:
          message: '🚨 ${{ github.event.repository.name }} : feedback report failed'
          hook: ${{ secrets.FEEDBACKS_HOOK }}
