name: 'User feedbacks report'

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run feedbacks report
        uses: ./.github/actions/feedbacks
        id: feedbacks-report
        env:
          GRIST_TABLE: ${{ secrets.GRIST_TABLE }}
          GRIST_API_KEY: ${{ secrets.GRIST_API_KEY }}

      - name: Post feedback report
        uses: ./.github/actions/notify
        with:
          message: '${{ steps.my-action.outputs.feedbacks }}'
          hook: ${{ secrets.TCHAP_HOOK }}
          id: ${{ secrets.TCHAP_ROOM_ID }}

      - name: Notify failure
        if: failure()
        uses: ./.github/actions/notify
        with:
          message: '🚨 ${{ github.event.repository.name }} : feedback report failed'
          hook: ${{ secrets.TCHAP_HOOK }}
          id: ${{ secrets.TCHAP_ROOM_ID }}
